name: ms_register
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  speech_to_text: ^6.6.1
  flutter_tts: ^4.0.2
  flutter_localization: ^0.2.0
  intl: ^0.19.0
  camera_web: ^0.3.3
  camera: ^0.11.0
  string_validator: ^1.1.0
  fluttertoast: ^8.2.5
  siri_wave: ^2.0.0+1
  dio: ^5.4.3+1
  provider: ^6.1.2
  firebase_core: ^2.31.1
  firebase_storage: ^11.7.6
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/svg/
    - assets/banner/
    - assets/image/
